import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { CarsProvider } from "../../providers/CarsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quadiro Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
  appearance={{
    variables: {
      colorText: '#ffffff',
      colorPrimary: '#1e90ff',
      colorBackground: '#1c1c1c', // Dark gray instead of pitch black
      colorInputBackground: '#2a2a2a', // Slightly lighter gray for input backgrounds
      colorInputText: '#ffffff',
      colorTextOnPrimaryBackground: '#ffffff'
    },
    elements: {
      socialButtonsBlockButton: 'bg-[#2a2a2a]',
      socialButtonsBlockButtonText: 'text-[#ffffff]',
      socialButtonsBlockButtonText__google: 'text-[#ffffff]',
      button: 'text-[#ffffff] hover:text-[#e0e0e0]',
      badge: 'text-[#ffffff]'
    }
  }}
>
      <body className={inter.className}>
      <CarsProvider>
        <main className="w-full h-full bg-[#0a0a0a]">
         {children}
        </main>
        </CarsProvider>
      </body>
      </ClerkProvider>
    </html>
  );
}
